apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  type: {{ .Values.backend.serviceType }}
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  selector:
    app: {{ .Release.Name }}-backend
