apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  type: {{ .Values.frontend.serviceType }}
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
    nodePort: 30080
  selector:
    app: {{ .Release.Name }}-frontend
