apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secrets
type: Opaque
stringData:
  username: {{ .Values.database.user | quote }}
  password: {{ .Values.database.password | quote }}
